// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA41IiJLTrlk56yQ0XCTZ4bx7nlTITCPEI',
    appId: '1:27583259432:android:2a6faedcd459729263261d',
    messagingSenderId: '27583259432',
    projectId: 'wishy-aeeb0',
    storageBucket: 'wishy-aeeb0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCV8TNtDGmye7-9hnHd1JQKqful3O8EKC4',
    appId: '1:27583259432:ios:fe4ec199fc6221e363261d',
    messagingSenderId: '27583259432',
    projectId: 'wishy-aeeb0',
    storageBucket: 'wishy-aeeb0.appspot.com',
    iosBundleId: 'com.example.flutterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCV8TNtDGmye7-9hnHd1JQKqful3O8EKC4',
    appId: '1:27583259432:ios:fe4ec199fc6221e363261d',
    messagingSenderId: '27583259432',
    projectId: 'wishy-aeeb0',
    storageBucket: 'wishy-aeeb0.appspot.com',
    iosBundleId: 'com.example.flutterApp',
  );
}
